title: Hachem Saddiki  # You can add your name here

logo: 1.jpg # Use a relative path to logo image 

description: Biostatistician specializing in epidemiology, furthering research in public health and medicine. 

#show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

#plugins:
#  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
